<script type="text/javascript">
// library name and id validation
$(document).ready(function() {
    $("#library_name").change(function(){
        if( (typeof(library) === "undefined") || (library.value != this.value) ){
            //todo: show warning and add library button
            $("#library_id").val(0);
        }
    });
});
</script>

<?php
if(is_array($this->errors )) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode(';', $error) . '<br />';
        }
    }
}

if(!empty($this->branch)) {
    foreach ($this->form->getSubForms() as $sform) {
        $sform->setDefaults($this->branch);
        $sform->removeElement('addBtn');
        $sform->removeElement('searchBtn');
    }
} else {
    foreach ($this->form->getSubForms() as $sform) {
        $sform->removeElement('deleteBtn');
        $sform->removeElement('updateBtn');
    } 
}
echo $this->form->render();

?><?php foreach ($this->branches as $branch): ?>
    <div>
        <?php if(is_array($this->libraries)): ?>
            <?php if ($this->libraries[$branch['id']]):?>
              <label> LibName: <?= $this->libraries[$branch['id']]->name; ?> </label>
            <?php endif;?>
        <?php endif;?>        
        <label> NAME : <?= $branch['name']; ?> </label>
        <label> ID : <?= $branch['id']; ?> </label>
        <label> Librari_ID : <?= $branch['library_id']; ?> </label>
        <a href="/branch/update/?id=<?= $branch['id'] ?>">update</a>
        <a href="/branch/delete/?id=<?= $branch['id'] ?>">delete</a>
    </div>
<?php endforeach; ?>