<script type="text/javascript">

$(document).ready(function() {
	$("#library_id").addEventListener('change', function(event){
	//	$("#library_id").val(0);
	});
	alert('hi!');
});
</script>

<?php
if(is_array($this->errors )) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode(';', $error) . '<br />';
        }
    }
}

if(!empty($this->branch)) {
    $this->form->setDefaults($this->branch->toArray());
    $this->form->subform->removeElement('addBtn');
    $this->form->subform->removeElement('searchBtn');
} else {
    $this->form->subform->removeElement('deleteBtn');
    $this->form->subform->removeElement('editBtn');
}
echo $this->form->render();

?><?php foreach ($this->branches as $branch): ?>
    <div>
        <?php if(is_array($this->libraries)): ?>
            <?php if ($this->libraries[$branch->id]):?>
              <label> LibName: <?= $this->libraries[$branch->id]->name; ?> </label>
            <?php endif;?>
        <?php endif;?>        
        <label> NAME : <?= $branch->name; ?> </label>
        <label> ID : <?= $branch->id; ?> </label>
        <label> Librari_ID : <?= $branch->library_id; ?> </label>
        <a href="/branch/update/?id=<?= $branch->id ?>">update</a>
        <a href="/branch/delete/?id=<?= $branch->id ?>">delete</a>
    </div>
<?php endforeach; ?>