<?php foreach ($this->authors as $author): ?>
    <div>
        <label> SURNAME : <?= $author->surname; ?> </label>
        <label> ID : <?= $author->id; ?> </label>
        <label> NAME : <?= $author->name; ?> </label>
        <label> PATRONYMIC : <?= $author->patronymic; ?> </label>
        <label> INITIALS : <?= $author->initials; ?> </label>
        <a href="/author/update/?id=<?= $author->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}

if(!empty($this->author)) {
    $this->form->setDefaults($this->author->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('updateBtn');
}
echo $this->form->render();