<?php foreach ($this->items as $item): ?>
    <div>
        <label> ID : <?= $item->id; ?> </label>
        <label> NAME : <?= $item->type_id; ?> </label>
        <a href="/item/update/?id=<?= $item->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}

if(!empty($this->item)) {
    foreach($this->form->getSubForms() as $sform){
        $sform->setDefaults($this->item->toArray());
        $sform->removeElement('addBtn');
        $sform->removeElement('searchBtn');
    }
} else {
    foreach($this->form->getSubForms() as $sform){
        $sform->removeElement('deleteBtn');
        $sform->removeElement('updateBtn');
    }
}
echo $this->form->render();