<?php foreach ($this->items as $item): ?>
    <div>
        <label> ID : <?= $item->id; ?> </label>
        <label> NAME : <?= $item->type_id; ?> </label>
        <a href="/item/update/?id=<?= $item->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}

if(!empty($this->item)) {
    $this->form->setDefaults($this->item->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('editBtn');
}
echo $this->form->render();