<form id="library" action="<?= $this->element->getAction(); ?>" 
                   method="<?= $this->element->getMethod(); ?>" >
<p>
    name<br />
    <?= $this->element->name; ?>
</p>
<p>
    name_short<br />
    <?= $this->element->name_short; ?>
</p>
<p>
    adress<br />
    <?= $this->element->adress; ?>
</p>
<p>
    note<br />
    <?= $this->element->note; ?>
</p>
<?= $this->element->submit; ?>