<?php foreach ($this->thesauruses as $thesaurus): ?>
    <div>
        <label> NAME : <?= $thesaurus->name; ?> </label>
        <label> ID : <?= $thesaurus->id; ?> </label>
        <a href="/thesaurus/update/?id=<?= $thesaurus->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}
if(!empty($this->thesaurus)) {
    $this->form->setDefaults($this->thesaurus->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('updateBtn');
}
echo $this->form->render();