<?php foreach ($this->thesauruses as $thesaurus): ?>
    <div>
        <label> NAME : <?= $thesaurus->name; ?> </label>
        <label> ID : <?= $thesaurus->id; ?> </label>
        <a href="/thesaurus/update/?id=<?= $thesaurus->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
//if(is_array($this->errors)) {
//    foreach ($this->errors as $name=>$error){
//        if(count($error)){
//            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
//        }
//    }
//}
if(!empty($this->thesaurus)) {
    foreach ($this->form->getSubForms() as $sform){
        $sform->setDefaults($this->thesaurus->toArray());
        $sform->removeElement('addBtn');
        $sform->removeElement('searchBtn');
    }
} else {
    foreach ($this->form->getSubForms() as $sform){
        $sform->removeElement('deleteBtn');
        $sform->removeElement('updateBtn');
        $sform->removeElement('indexBtn');
    }
}
echo $this->form->render();