<?php foreach ($this->noteTypes as $noteType): ?>
    <div>
        <label> ID : <?= $noteType->id; ?> </label>
        <label> NAME : <?= $noteType->name; ?> </label>
        <a href="/note-type/update/?id=<?= $noteType->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}

if(!empty($this->noteType)) {
    $this->form->setDefaults($this->noteType->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('editBtn');
}
echo $this->form->render();