<?php foreach ($this->languages as $language): ?>
    <div>
        <label> NAME : <?= $language->name; ?> </label>
        <label> ID : <?= $language->id; ?> </label>
        <label> short : <?= $language->name_short; ?> </label>
        <label> ISO2 : <?= $language->iso2; ?> </label>
        <label> ISO3 : <?= $language->iso3; ?> </label>
        <a href="/language/update/?id=<?= $language->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}
if(!empty($this->language)) {
    $this->form->setDefaults($this->language->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('editBtn');
}
echo $this->form->render();