<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}
if(!empty($this->country)) {
    $this->form->setDefaults($this->country->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('updateBtn');
}
echo $this->form->render();
?><?php foreach ($this->countries as $country): ?>
    <div>
        <label> NAME : <?= $country->name; ?> </label>
        <label> ID : <?= $country->id; ?> </label>
        <label> short : <?= $country->name_short; ?> </label>
        <label> ISO2 : <?= $country->iso2; ?> </label>
        <label> ISO3 : <?= $country->iso3; ?> </label>
        <a href="/country/update/?id=<?= $country->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>
