<?php foreach ($this->types as $type): ?>
    <div>
        <label> ID : <?= $type->id; ?> </label>
        <label> NAME : <?= $type->name; ?> </label>
        <a href="/type/update/?id=<?= $type->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
if(is_array($this->errors)) {
    foreach ($this->errors as $name=>$error){
        if(count($error)){
            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
        }
    }
}

if(!empty($this->type)) {
    $this->form->setDefaults($this->type->toArray());
    $this->form->removeElement('addBtn');
    $this->form->removeElement('searchBtn');
} else {
    $this->form->removeElement('deleteBtn');
    $this->form->removeElement('updateBtn');
}
echo $this->form->render();