<?php foreach ($this->rubrics as $rubric): ?>
    <div>
        <label> ID : <?= $rubric->id; ?> </label>
        <label> NAME : <?= $rubric->name; ?> </label>
        <a href="/rubric/update/?id=<?= $rubric->id; ?>">редактировать</a>
    </div>
<?php endforeach; ?>

<?php 
//if(is_array($this->errors)) {
//    foreach ($this->errors as $name=>$error){
//        if(count($error)){
//            echo 'ошибка в поле ' . $name .': ' . implode('; ', $error) . '<br />';
//        }
//    }
//}
if(!empty($this->rubric)) {
   $data = $this->rubric->toArray();
   $data['thesaurus_name'] = $this->thesaurus->name;
}

if(!empty($this->rubric)) {
    foreach ($this->form->getSubForms() as $sform){
        $sform->setDefaults($data);
        $sform->removeElement('addBtn');
        $sform->removeElement('searchBtn');
    }
} else {
    foreach ($this->form->getSubForms() as $sform){
        $sform->removeElement('deleteBtn');
        $sform->removeElement('updateBtn');
        $sform->removeElement('indexBtn');
    }
}
echo $this->form->render();